apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ecomm-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecomm-backend
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 20
