apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-backend
  labels:
    app: ecomm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomm-app
      tier: backend
  template:
    metadata:
      labels:
        app: ecomm-app
        tier: backend
    spec:
      containers:
      - name: ecomm-backend
        image: [BACKEND_IMAGE_IDENTIFIER]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 500m
        env:
          - name: GCLOUD_PROJECT
            value: [GCLOUD_PROJECT]
          - name: GCLOUD_BUCKET
            value: [GCLOUD_BUCKET]
            
