apiVersion: v1
kind: Service
metadata:
  name: ecomm-frontend
  labels:
    app: ecomm-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: ecomm-app
    tier: frontend