apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-frontend
  labels:
    app: ecomm-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecomm-app
      tier: frontend
  template:
    metadata:
      labels:
        app: ecomm-app
        tier: frontend
    spec:
      containers:
      - name: ecomm-frontend
        image: [FRONTEND_IMAGE_IDENTIFIER]
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 500m
        env:
          - name: GCLOUD_PROJECT
            value: [GCLOUD_PROJECT]
          - name: GCLOUD_BUCKET
            value: [GCLOUD_BUCKET]
